### ISSUE TITLE
عدم اضافه شدن به لیست تمپلیت ها

### ISSUE THREAD

**Issue by ali-kh84** [rabbal/DNTFrameworkCore#10]
سلام
بعد از اجرای دستور
dotnet new --install DNTFrameworkCoreTemplateAPI::*
به لیست تمپلیت ها اضافه نمیشه 
ورژن استفاده شده برای dotnetcore 3.1.100

**Comment by rabbal** [comment]
Try to install new version of this template via: dotnet new --install DNTFrameworkCoreTemplateAPI::5.1.0
