### ISSUE TITLE
پروژه تمپلیت نیاز به بروزرسانی دارد

### ISSUE THREAD

**Issue by reisi-h** [rabbal/DNTFrameworkCore#13]
سلام
تشکر بابت این کار بسیار بزرگ و عالی
در سولوشن تمپلیت
(`templates/aspnet-core`) 
و پروژه کتابخانه 
(`ProjectName.Application`) 
در فایل های
 `[Identity/RoleService.cs](https://github.com/rabbal/DNTFrameworkCore/blob/master/templates/aspnet-core/src/ProjectName.Application/Identity/RoleService.cs)`
و همچنین
 `[Identity/UserService.cs](https://github.com/rabbal/DNTFrameworkCore/blob/master/templates/aspnet-core/src/ProjectName.Application/Identity/UserService.cs)` 
مشکل رفرنس به پروژه
 DNTFrameworkCore 
دارند. فضای نام 
`DNTFrameworkCore.Application.Services` 
دیگه وجود نداره و تغییراتی داشته که این تغییرات بر روی این دو فایل اعمال نشده است.

**Comment by rabbal** [comment]
Try to install new version of this template via: dotnet new --install DNTFrameworkCoreTemplateAPI::5.1.0
