### ISSUE TITLE
How user can register

### ISSUE THREAD

**Issue by MHKarami97** [rabbal/DNTFrameworkCore#5]
Hi. Is there any API like login that user can register to app?

Also what is these lines do in appsetting:
"UserSeed": {
    "UserName": "Admin",
    "Password": "123@456#Pass",
    "DisplayName": "مدیر سیستم"
  }

**Comment by rabbal** [comment]
Hi @MHKarami97
- No there is not; you can implemet it
- This information used for seed admin account
