### ISSUE TITLE
Generate Unique DocNumber

### ISSUE THREAD

**Issue by irajchardoli** [rabbal/DNTFrameworkCore#9]
salam
Aghaye rabbal man ba tavajoh be matlabe montashe shode dar site [dotnettips](https://www.dotnettips.info/post/2918/%d8%b7%d8%b1%d8%a7%d8%ad%db%8c-%d9%88-%d9%be%db%8c%d8%a7%d8%af%d9%87-%d8%b3%d8%a7%d8%b2%db%8c-%d8%b2%db%8c%d8%b1%d8%b3%d8%a7%d8%ae%d8%aa%db%8c-%d8%a8%d8%b1%d8%a7%db%8c-%d8%aa%d9%88%d9%84%db%8c%d8%af-%d8%ae%d9%88%d8%af%da%a9%d8%a7%d8%b1-%da%a9%d8%af-%d9%85%d9%86%d8%ad%d8%b5%d8%b1-%d8%a8%d9%87-%d9%81%d8%b1%d8%af-%d8%af%d8%b1-%d8%b2%d9%85%d8%a7%d9%86-%d8%ab%d8%a8%d8%aa-%d8%b1%da%a9%d9%88%d8%b1%d8%af-%d8%ac%d8%af%db%8c%d8%af) yek soal daram .

Agar man 2 ta publish joda az application dashte basham ba db moshtarak in matlab bahse hamzamani ro mitoone handle kone? ya bayad ino samte Database handle konam?

**Comment by rabbal** [comment]
<div dir="rtl">

سلام؛ در آن مطلب اشاره شد از [sp_getapplock](https://www.mssqltips.com/sqlservertip/3202/prevent-multiple-users-from-running-the-same-sql-server-stored-procedure-at-the-same-time/) برای ایجاد فقل منطقی در سطح نرم‌ افزار استفاده می‌شود که یک راه حل مبتنی‌بر بانک اطلاعاتی می‌باشد.
